### ISSUE TITLE
Misconfigured certs for `cc_bridge_cc_uploader`, `cc_bridge_cc_uploader_server` and `cc_bridge_tps`?

### ISSUE THREAD

**Issue by rkoster** [genesis-community/cf-genesis-kit#112]
Currently `cc_bridge_cc_uploader`, `cc_bridge_cc_uploader_server` and `cc_bridge_tps`, seem to use the same `cc_bridge_tps` certificate:
```yaml
      cc_bridge_cc_uploader:
        ca_cert:     (( grab meta.certs.cf_internal.ca.cert ))
        client_cert: (( vault meta.vault "/cf_internal/certs/cc_bridge_tps:certificate" ))
        client_key:  (( vault meta.vault "/cf_internal/certs/cc_bridge_tps:key" ))
      cc_bridge_cc_uploader_server:
        ca_cert:     (( grab meta.certs.cf_internal.ca.cert ))
        server_cert: (( vault meta.vault "/cf_internal/certs/cc_bridge_tps:certificate" ))
        server_key:  (( vault meta.vault "/cf_internal/certs/cc_bridge_tps:key" ))
      cc_bridge_tps:
        ca_cert:     (( grab meta.certs.cf_internal.ca.cert ))
        client_cert: (( vault meta.vault "/cf_internal/certs/cc_bridge_tps:certificate" ))
        client_key:  (( vault meta.vault "/cf_internal/certs/cc_bridge_tps:key" ))
```
Source: https://github.com/genesis-community/cf-genesis-kit/blob/master/manifests/cf/certs.yml#L17-L28 and 

In cf-deployment these are different:
```yaml
  - name: cc_uploader
    release: capi
    properties:
      capi:
        cc_uploader:
          cc:
            ca_cert: "((cc_bridge_cc_uploader.ca))"
            client_cert: "((cc_bridge_cc_uploader.certificate))"
            client_key: "((cc_bridge_cc_uploader.private_key))"
          mutual_tls:
            ca_cert: "((cc_bridge_cc_uploader_server.ca))"
            server_cert: "((cc_bridge_cc_uploader_server.certificate))"
            server_key: "((cc_bridge_cc_uploader_server.private_key))"
...
  - name: tps
    release: capi
    properties:
      capi:
        tps:
          bbs: *diego_bbs_client_properties
          watcher:
            locket:
              api_location: "locket.service.cf.internal:8891"
            skip_consul_lock: true
          cc:
            ca_cert: "((cc_bridge_tps.ca))"
            client_cert: "((cc_bridge_tps.certificate))"
            client_key: "((cc_bridge_tps.private_key))"
```
Source: https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L1024-L1031 and https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L1024-L1031

After updating the cf-deployment I'm getting:
```
   -----> Creating runtime environment
   -----> Saving vendor_bundle to cache
   -----> Finalizing Ruby
   -----> Copy binaries to app/bin directory
   Exit status 0
   Uploading droplet, build artifacts cache...
   Uploading build artifacts cache...
   Uploading droplet...
   Failed to upload payload for build artifacts cache
   Failed to upload payload for droplet
   Uploading failed
   Cell c27aa218-01a8-4d6b-8942-d26463de182f stopping instance 644c400e-2c3a-4359-a2af-c04774fc14a0
   Cell c27aa218-01a8-4d6b-8942-d26463de182f destroying container for instance 644c400e-2c3a-4359-a2af-c04774fc14a0
Error staging application: Staging error: staging failed
FAILED
```
Rep log:
```
==> /var/vcap/sys/log/rep/rep.stdout.log <==
{"timestamp":"2020-02-10T15:35:39.101631738Z","level":"error","source":"rep","message":"rep.URLUploader.failed-uploading","data":{"attempt":2,"error":"Post https://cc-uploader.service.cf.internal:9091/v1/build_artifacts/644c400e-2c3a-4359
-a2af-c04774fc14a0?cc-build-artifacts-upload-uri=https%3A%2F%2Fcloud-controller-ng.service.cf.internal%3A9023%2Finternal%2Fv4%2Fbuildpack_cache%2Fcflinuxfs3%2F0a9825b7-a42d-498d-b9ee-b2a002dfe42c%2Fupload\u0026timeout=900: x509: certifica
te is valid for tps_watcher, not cc-uploader.service.cf.internal","fileLocation":"/var/vcap/data/rep/tmp/executor-work/compressed544405402","session":"2"}}
{"timestamp":"2020-02-10T15:35:39.101734676Z","level":"error","source":"rep","message":"rep.URLUploader.failed-all-upload-attempts","data":{"error":"Post https://cc-uploader.service.cf.internal:9091/v1/build_artifacts/644c400e-2c3a-4359-a
2af-c04774fc14a0?cc-build-artifacts-upload-uri=https%3A%2F%2Fcloud-controller-ng.service.cf.internal%3A9023%2Finternal%2Fv4%2Fbuildpack_cache%2Fcflinuxfs3%2F0a9825b7-a42d-498d-b9ee-b2a002dfe42c%2Fupload\u0026timeout=900: x509: certificate
 is valid for tps_watcher, not cc-uploader.service.cf.internal","fileLocation":"/var/vcap/data/rep/tmp/executor-work/compressed544405402","session":"2"}}
{"timestamp":"2020-02-10T15:35:39.101795065Z","level":"error","source":"rep","message":"rep.executing-container-operation.task-processor.run-container.containerstore-run.node-run.action.upload-step.failed-to-upload","data":{"container-gui
d":"644c400e-2c3a-4359-a2af-c04774fc14a0","container-state":"reserved","error":"Post https://cc-uploader.service.cf.internal:9091/v1/build_artifacts/644c400e-2c3a-4359-a2af-c04774fc14a0?cc-build-artifacts-upload-uri=https%3A%2F%2Fcloud-co
ntroller-ng.service.cf.internal%3A9023%2Finternal%2Fv4%2Fbuildpack_cache%2Fcflinuxfs3%2F0a9825b7-a42d-498d-b9ee-b2a002dfe42c%2Fupload\u0026timeout=900: x509: certificate is valid for tps_watcher, not cc-uploader.service.cf.internal","from
":"/tmp/output-cache","guid":"644c400e-2c3a-4359-a2af-c04774fc14a0","session":"32.1.3.3.1.1.4"}}
{"timestamp":"2020-02-10T15:35:39.114374905Z","level":"error","source":"rep","message":"rep.URLUploader.failed-uploading","data":{"attempt":2,"error":"Post https://cc-uploader.service.cf.internal:9091/v1/droplet/644c400e-2c3a-4359-a2af-c0
4774fc14a0?cc-droplet-upload-uri=https%3A%2F%2Fcloud-controller-ng.service.cf.internal%3A9023%2Finternal%2Fv4%2Fdroplets%2F644c400e-2c3a-4359-a2af-c04774fc14a0%2Fupload\u0026timeout=900: x509: certificate is valid for tps_watcher, not cc-
uploader.service.cf.internal","fileLocation":"/var/vcap/data/rep/tmp/executor-work/compressed921214311","session":"2"}}
{"timestamp":"2020-02-10T15:35:39.114480311Z","level":"error","source":"rep","message":"rep.URLUploader.failed-all-upload-attempts","data":{"error":"Post https://cc-uploader.service.cf.internal:9091/v1/droplet/644c400e-2c3a-4359-a2af-c047
74fc14a0?cc-droplet-upload-uri=https%3A%2F%2Fcloud-controller-ng.service.cf.internal%3A9023%2Finternal%2Fv4%2Fdroplets%2F644c400e-2c3a-4359-a2af-c04774fc14a0%2Fupload\u0026timeout=900: x509: certificate is valid for tps_watcher, not cc-up
loader.service.cf.internal","fileLocation":"/var/vcap/data/rep/tmp/executor-work/compressed921214311","session":"2"}}
{"timestamp":"2020-02-10T15:35:39.114518403Z","level":"error","source":"rep","message":"rep.executing-container-operation.task-processor.run-container.containerstore-run.node-run.action.upload-step.failed-to-upload","data":{"container-gui
d":"644c400e-2c3a-4359-a2af-c04774fc14a0","container-state":"reserved","error":"Post https://cc-uploader.service.cf.internal:9091/v1/droplet/644c400e-2c3a-4359-a2af-c04774fc14a0?cc-droplet-upload-uri=https%3A%2F%2Fcloud-controller-ng.serv
ice.cf.internal%3A9023%2Finternal%2Fv4%2Fdroplets%2F644c400e-2c3a-4359-a2af-c04774fc14a0%2Fupload\u0026timeout=900: x509: certificate is valid for tps_watcher, not cc-uploader.service.cf.internal","from":"/tmp/droplet","guid":"644c400e-2c
3a-4359-a2af-c04774fc14a0","session":"32.1.3.3.1.1.3"}}
```
