### ISSUE TITLE
networking-policy fails with 502 due to misconfigured port expects tls

### ISSUE THREAD

**Issue by ramonskie** [genesis-community/cf-genesis-kit#113]
the router expects a tls connection but genesis is configured with a https connectionwhich results in a 502

we need to add/replace the following in to the route_registar 
```
name: policy-server            
  tls_port: 4002            
  server_cert_domain:
```
example:
```
- name: api
    jobs:
    - name: route_registrar
      properties:
        route_registrar:
          routes:
          - name: policy-server
            tls_port: 4002
            server_cert_domain_san: api.system.cf.domain.starkandwayne.com
```
