### ISSUE TITLE
UAA SAML integration needs to be upgraded and improved

### ISSUE THREAD

**Issue by xiujiao** [genesis-community/cf-genesis-kit#16]
1) UAA SAML integration need to be consistent with specs in the UAA release version we used
2) At the moment, we need to add the following in the env file to add SAML integration

```
name: uaa
jobs: 
- name: uaa
instance_groups:
- name: uaa
  jobs:
  - name: uaa
    properties:
      login:
        saml:
          # Provider Information Configs
          providers:
            # Example
            myPvovider:
              nameID: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
              idpMetadata: the matadata itself or the link to it
              showSamlLoginLink: true
              linkText: Log in with XX IDP
              metadataTrustCheck: false
  
          #The active key is used for signing messages and the key to be used to encrypt messages.
          activeKeyId: key1
          keys:
            key1:
              key: (( vault secret/your-cf-env-vault-path/uaa/certs/server:key ))
              certificate: (( vault secret/your-cf-env-vault-path/uaa/certs/server:certificate ))
              passphrase: ""
            # you can add multiple keys such as key1, key2... 

```
The configuration should be simplified.
