### ISSUE TITLE
2.0.2 instance types/counts + blueprint hook

### ISSUE THREAD

**Issue by michaelmccaskill** [genesis-community/cf-genesis-kit#160]
The [`blueprint` hook](https://github.com/genesis-community/cf-genesis-kit/blob/master/hooks/blueprint#L464-L549) tries to find instance counts/types and ultimately puts them in a runtime generated ops file. Unfortunately, this prevents me from using the same params concept for my counts/types for my isolation segments since it will error with:

```
[ERROR] No such instance group <instance I want> - cannot change instance counts to 6.
        Valid instance groups are:
          nats, diego-cell, diego-api, uaa, scheduler, router, api, cc-worker, adapter,
          doppler, log-api, tcp-router, credhub, haproxy
[ERROR] Could not determine which YAML files to merge: 'blueprint' hook exited with 1:
```

**Comment by dennisjbell** [comment]
Yes, in this case, since you are already specifying the instance group directly in your environment, you can specify the instance count directly inside its yaml block, and don't need to use the params helpers.  Please let me know if that is not acceptable, and why.

**Comment by michaelmccaskill** [comment]
I'm using my own ops file for creating an isolation segment. Something like this:
```
instance_groups:
- .: (( inject instance_groups.diego-cell ))
  name: system-diego-cell
  instances: (( grab params.system-diego-cell_instance_count || meta.defaults.system-diego-cell_instance_count ))
```
If I use `params.system-diego-cell_instances` the `blueprint` hook freaks out. I got around it by having to rename my parameter, which isn't great. My point is the `blueprint` hook shouldn't prevent me from using a preferred paradigm.
