### ISSUE TITLE
Using self-signed certs with MinIO blobstore

### ISSUE THREAD

**Issue by a2geek** [genesis-community/cf-genesis-kit#172]
This is likely mostly some documentation note for other users/tinkerers. If you are using self-signed certificates (like using the `minio-genesis-kit`), there are a couple of different patches that need to be added.

For the environment configuration, Fog does have the capability to ignore the self-signed certificate:
```
bosh-variables:
  fog_connection:
    connection_options:
      ssl_verify_peer: false
```

But, in addition, the `rep` needs to also be told to allow the self-signed certificate (yaml-patch syntax):
```
---
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/diego/ssl?/skip_cert_verify
  value: true
```
 This wasn't obvious and hopefully saves somebody else spending time tracking those details down.
