### ISSUE TITLE
Route Service feature seems to be misconfigured

### ISSUE THREAD

**Issue by vorbidan** [genesis-community/cf-genesis-kit#93]
Reading [cf docs](https://docs.cloudfoundry.org/services/route-services.html#enabling-route-services-in-cloudfoundry), one may assume that route services are enabled when 
```
properties:
 router:
   route_services_secret: YOUR-SECRET-PASSPHRASE
```
is set in the `router` instance group for `gorouter` job. 

Indeed this is what we see in [cf-genesis-kit/manifests/cf/router.yml](https://github.com/genesis-community/cf-genesis-kit/blob/9e4fef13cb11e3805f3d7e197fabc397bc934a35/manifests/cf/router.yml#L21

This, however, does not enable route service support, and all attempts to create a user-provided-service with `-r` option fail with error, to the effect of "Support for route services is disabled. This service instance cannot be bound to a route."

It looks like Route Service will be enabled when the following configuration is applied to the `api` instance group:
```
jobs: 
- name: cloud_controller_ng
  properties:
    router:
      route_services_secret: (( vault meta.vault "/gorouter/route_services:secret" ))
```
